POST http://localhost:3003/api/blogs 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBhYXZvIiwiaWQiOiI1ZWE4NTY3MWM2ZGViYjY2MTZiYWIxOGUiLCJpYXQiOjE1ODg3NzUxMTV9.g5GLw7gcZg_WDRXJTVdhjYhOwDbfJX58GFGXvxK2J44

{
"title": "Joku", "author": "Paavo", "url": "hymy.fi", "likes": 21
}